kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3
source: [your repo's top level directory]
uses_cvs: false
plugins:
  - rubygems-sandbox
  - executable-hooks
  
